version: '3.8'

services:
  onboarding_dude_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    user: node
    tty: true
    stdin_open: true
    ports:
      - ${PORT}:${PORT}
    networks:
      - onboarding-network
    volumes:
      - .:/home/node/workspace/onboarding_dude

  onboarding_dude_db:
    image: postgres:13
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - onboarding-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch_onboard:
    container_name: elasticsearch_onboard
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=p4l4vr4m4g1c4
    networks:
      - onboarding-network

  kibana_onboard:
    container_name: kibana_onboard
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=p4l4vr4m4g1c4
    networks:
      - onboarding-network

networks:
  onboarding-network:
    driver: bridge

volumes:
  pgdata:
  es_data:
